#!/usr/bin/with-contenv sh

cd /usr/local/src/notomaton
exec gunicorn \
    --bind "0.0.0.0:80" \
    --workers 1 \
    --certfile /lego/certificates/${LEGO_DOMAINS}.crt \
    --keyfile /lego/certificates/${LEGO_DOMAINS}.pem \
    notomaton.app:app


#    --worker-class eventlet \
